@echo off   
ECHO Navigating to VSCODE Path 
cd E:\ANGULAR_POC_DEMO\PortableVSCODE\VSCode-win32-x64-1.51.1
d:
ECHO OPENING VSCODE WITH EXTENSION INSTALLED
code E:\ANGULAR_POC_DEMO\MY_APP1 --disable-gpu
ECHO ALL SET!
exit /b